name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log into Docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker Image
      working-directory: myproject/

      run: | 
        IMAGE_NAME=pizzaapp
        docker build . -f Dockerfile -t $DOCKER_REGISTRY/$IMAGE_NAME:latest
        docker push $DOCKER_REGISTRY/$IMAGE_NAME:latest
