# Generated by Django 5.0.7 on 2024-07-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('Margherita', 'Margherita'), ('Pepperoni', 'Pepperoni'), ('Vegetarian', 'Vegetarian')], default='Pepperoni', max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
